### ISSUE TITLE
Crash: app crashes when there is no price for an Offer

### ISSUE THREAD

**Issue by Johney9** [milekuglas/SellApp#21]
When the price is null or non existent in the database, the app crashes with NullPointerException at OffersAdapter.
Error message:

E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.app.sell, PID: 29395
                  java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Double.toString()' on a null object reference
                      at com.app.sell.adapter.OffersAdapter.getView(OffersAdapter.java:66)
                      at android.widget.AbsListView.obtainView(AbsListView.java:2372)
                      at android.widget.GridView.makeAndAddView(GridView.java:1439)
                      at android.widget.GridView.makeRow(GridView.java:366)
                      at android.widget.GridView.fillDown(GridView.java:307)
                      at android.widget.GridView.fillFromTop(GridView.java:442)
                      at android.widget.GridView.layoutChildren(GridView.java:1305)
                      at android.widget.AbsListView.onLayout(AbsListView.java:2171)
                      at android.view.View.layout(View.java:19590)
                      at android.view.ViewGroup.layout(ViewGroup.java:6053)
                      at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
                      at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
                      at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
                      at android.view.View.layout(View.java:19590)
                      at android.view.ViewGroup.layout(ViewGroup.java:6053)
                      at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                      at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                      at android.view.View.layout(View.java:19590)
                      at android.view.ViewGroup.layout(ViewGroup.java:6053)
                      at android.support.constraint.ConstraintLayout.onLayout(ConstraintLayout.java:1855)
                      at android.view.View.layout(View.java:19590)
                      at android.view.ViewGroup.layout(ViewGroup.java:6053)
                      at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                      at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                      at android.view.View.layout(View.java:19590)
                      at android.view.ViewGroup.layout(ViewGroup.java:6053)
                      at android.support.v7.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:443)
                      at android.view.View.layout(View.java:19590)
                      at android.view.ViewGroup.layout(ViewGroup.java:6053)
                      at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                      at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                      at android.view.View.layout(View.java:19590)
                      at android.view.ViewGroup.layout(ViewGroup.java:6053)
                      at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
                      at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
                      at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
                      at android.view.View.layout(View.java:19590)
                      at android.view.ViewGroup.layout(ViewGroup.java:6053)
                      at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                      at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                      at com.android.internal.policy.DecorView.onLayout(DecorView.java:758)
                      at android.view.View.layout(View.java:19590)
                      at android.view.ViewGroup.layout(ViewGroup.java:6053)
                      at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2484)
                      at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2200)
                      at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1386)
                      at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6733)
                      at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
                      at android.view.Choreographer.doCallbacks(Choreographer.java:723)
                      at android.view.Choreographer.doFrame(Choreographer.java:658)
                      at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
                      at android.os.Handler.handleCallback(Handler.java:789)
                      at android.os.Handler.dispatchMessage(Handler.java:98)
                      at android.os.Looper.loop(Looper.java:164)
                      at android.app.ActivityThread.main(ActivityThread.java:6541)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

**Comment by milekuglas** [comment]
@arsa94 , Don't allow creating offers without a price.
